In [7]:
import numpy as np
# adding two lists in python

sum = [] 
l1 = [1, 2, 3]

l2 = [2, 3, 4]

for i in range(len(l1)):

    sum.append(l1[i]+l2[i])
print(sum)
# adding in numpy

a1 = np.arange(3)

a2 = np.arange(3)

sum2 = a1+a2

print (sum)

[3, 5, 7]
[3, 5, 7]


In [8]:
np.random.randn(100)

array([ 0.46863812,  0.43098804, -1.03329468,  0.81058277, -1.7896862 ,
       -0.63601768,  1.00055679, -0.5057386 , -0.77324216, -0.14043474,
        1.41829747, -0.94844454, -0.21246714, -0.79778108, -0.71240512,
        0.46064264,  1.2289057 ,  0.74645576,  0.71413501,  0.34096676,
       -0.79583866, -1.6874965 ,  0.26004988, -1.36701235, -0.3193185 ,
       -0.85282856, -0.60761676,  0.63818878, -0.35540402, -0.27394464,
        0.24926277,  0.73604987, -0.81154786, -3.25106462, -0.59859539,
        0.73924494,  0.5930741 ,  0.7641016 ,  0.24013515, -1.1222538 ,
        0.06667581, -0.21598345, -1.66917143, -0.60192437, -0.2045148 ,
       -0.19474202, -0.52060435,  0.14055552, -1.94973959, -1.49592898,
       -0.70434253, -1.07134061, -0.61390846,  1.13262558,  0.5692862 ,
       -1.31355329,  0.70040586, -1.65638554,  0.54564527,  1.7612448 ,
       -0.5163636 , -0.01978168, -1.48105971,  1.42922263, -0.99316903,
        1.39752874, -0.09885951, -1.51097452,  1.12035452,  1.35

In [13]:
#comparing the dot product
import numpy as np
from datetime import datetime
a=np.random.randn(100)
b=np.random.randn(100)
T=10000
def slow_dot_product(a,b):
    result=0
    for e,f in zip(a,b):
        result+=e*f
    return result
t0=datetime.now()
for t in range (T):
    slow_dot_product(a,b)
    dt1=datetime.now()-t0
for t in range(T):
    c=a.dot(b)
print(c)
d=slow_dot_product(a,b)
print(d)
    

6.20885800892
6.20885800892


In [17]:
# Generating One Diamensional Data
import numpy as np
import pandas as pd
N=10
with open ('data_1d.csv','w') as f:
    X=np.random.randn(N)
    Y=2*X+1+np.random.normal(scale=4 ,size=N)
    for i in range(N):
        f.write("%s%s\n"% (X[i],Y[i]))
        

In [18]:
print(Y)

[  4.93791138  11.92134387   5.77703617  -0.18741276  -5.54101771
  -2.74758705  -0.73846241  -2.13764765   8.01350778   3.92875433]


In [16]:
print(X)

[-0.79716557  0.38008057 -0.27971669  1.58981709 -0.31773406 -1.23660679
  0.69242434  0.04954028  1.20802368 -1.04733744]


In [21]:
import numpy as np

N = 5
w = np.array([2, 3])
with open('data_2d.csv', 'w') as f:
    X = np.random.uniform(low=0, high=100, size=(N,2))
    Y = np.dot(X,w) + 1 + np.random.normal(scale=3, size=N)
    for i in range(N):
        f.write("%s,%s,%s\n" % (X[i,0], X[i,1], Y[i]))
print(X)
print(Y)

[[ 38.35277869  91.04100075]
 [ 30.73499859  97.93597793]
 [ 15.42281863  68.27895389]
 [ 50.63587896  40.42829666]
 [ 88.36423523  87.43492578]]
[ 352.06752673  351.65255582  235.37604094  225.27412151  440.91589458]


In [23]:
np.shape(X)

(5, 2)

In [24]:
np.shape(w)

(2,)

In [25]:
np.dot(X,w)

array([ 349.82855964,  355.27793098,  235.68249894,  222.55664791,
        439.0332478 ])

In [29]:
X

array([[ 38.35277869,  91.04100075],
       [ 30.73499859,  97.93597793],
       [ 15.42281863,  68.27895389],
       [ 50.63587896,  40.42829666],
       [ 88.36423523,  87.43492578]])

In [30]:
X.reshape(2,5)

array([[ 38.35277869,  91.04100075,  30.73499859,  97.93597793,
         15.42281863],
       [ 68.27895389,  50.63587896,  40.42829666,  88.36423523,
         87.43492578]])

In [31]:
X.T

array([[ 38.35277869,  30.73499859,  15.42281863,  50.63587896,
         88.36423523],
       [ 91.04100075,  97.93597793,  68.27895389,  40.42829666,
         87.43492578]])