In [45]:
import numpy as np
N=100
D=2
X=np.random.randn(N,D)
#Nnp.random.randn gives a random distribution of mean zero and varience 1.

1.0341012555628775

In [43]:
print(X)

[[ 0.13928241  0.76725579]
 [-1.0113489  -0.49214884]
 [ 0.76161704  0.46163377]
 [-0.52619407 -0.61046251]
 [-0.92624523  0.64935809]
 [-0.65390542  1.80650857]
 [-0.17327221  0.17608993]
 [ 1.16186692 -0.71868992]
 [ 0.17448254 -0.45349265]
 [-1.120966   -0.44116918]
 [-1.32684633 -0.61343615]
 [ 0.60767538 -0.01519595]
 [ 1.08420029  0.72991845]
 [-0.20291734  2.87266705]
 [ 0.03978533  1.31087028]
 [ 1.12135303  0.08379187]
 [ 1.29124167  0.27422274]
 [ 1.53303051  1.53815253]
 [ 1.42262819 -0.40116103]
 [-0.31434932 -0.24965994]
 [-0.55569141  1.17388903]
 [ 1.02740488  1.05998196]
 [ 3.46675456  0.76594575]
 [-1.44269249 -0.27944157]
 [-1.06608253 -0.38409193]
 [-1.31126725 -2.06171706]
 [-0.38253511 -1.516898  ]
 [ 0.97886457  0.26553893]
 [ 0.29235151 -0.21895034]
 [-0.13780742 -2.50483209]
 [-1.06649517 -0.13477889]
 [-1.59441469  0.02115722]
 [-0.45575942 -0.35870947]
 [ 0.15392721  1.82207041]
 [-0.14718167  0.52019103]
 [-0.8335408  -1.07131963]
 [ 0.10507443 -0.02607787]
 

In [3]:
ones=np.ones((N,1))
ones

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
      

In [4]:
Xb=np.concatenate((ones,X),axis=1)
Xb

array([[ 1.        , -0.8587495 , -1.07006788],
       [ 1.        , -0.04879315, -0.12498338],
       [ 1.        ,  0.5115163 ,  0.76278924],
       [ 1.        , -0.71833777, -0.83546165],
       [ 1.        , -2.10853511, -1.35170822],
       [ 1.        , -0.06154242, -0.10793566],
       [ 1.        , -0.62042631,  0.88261744],
       [ 1.        , -2.09687287,  0.39969964],
       [ 1.        , -0.66292663, -0.16777148],
       [ 1.        , -2.12552488, -0.45383066],
       [ 1.        ,  1.11123565,  0.77244739],
       [ 1.        ,  0.09818253,  1.17155373],
       [ 1.        , -1.29858733, -0.87635247],
       [ 1.        , -1.07964163, -0.17177736],
       [ 1.        , -0.68400921, -0.57483023],
       [ 1.        ,  1.30753243, -0.11385845],
       [ 1.        , -0.60567045,  0.66812126],
       [ 1.        ,  0.79306756, -2.64381694],
       [ 1.        ,  1.0528327 , -0.38357732],
       [ 1.        ,  0.90283755, -0.15875659],
       [ 1.        , -0.67025458, -0.208

In [56]:
w = np.random.randn((D+1))


In [57]:
np.var(w)

0.59257599457173971

In [7]:
np.ndim(w)

1

In [59]:
print(np.shape(w))
print(np.shape(Xb))

(3,)
(10, 3)


In [60]:
z=Xb.dot(w)
print(np.shape(z))

(10,)


In [61]:
z

array([ 0.22606421,  1.26466233,  0.79111498,  1.15493979,  1.99811944,
        2.6354037 ,  1.60109071,  1.39600693,  1.80452295,  1.52452115])

In [65]:
def sigmoid (z):
    return 1/(1+np.exp(z+1))
sigmoid(z)

array([ 0.22687102,  0.0940922 ,  0.14293608,  0.10387052,  0.0475109 ,
        0.02569561,  0.06906826,  0.0834777 ,  0.05708025,  0.07415694])

In [83]:
X=np.random.randint(100, size=(10,2))
X

array([[ 0, 96],
       [39, 55],
       [37,  7],
       [50, 28],
       [68, 88],
       [61, 20],
       [ 9, 76],
       [69,  7],
       [30, 25],
       [29, 26]])

In [85]:
X[:,:1]=X[:, :1]+np.ones((10,1))
X


array([[ 1, 96],
       [40, 55],
       [38,  7],
       [51, 28],
       [69, 88],
       [62, 20],
       [10, 76],
       [70,  7],
       [31, 25],
       [30, 26]])

In [92]:
X[4,1]

88

In [93]:
X[1,1]

55

In [94]:
X[1:2,0:1]

array([[40]])

In [95]:
X[0:1,0:1]

array([[1]])

In [103]:
X[0:2,1:]

array([[96],
       [55]])

In [107]:
X[0:2,0:1]

array([[ 1],
       [40]])

In [108]:
X[0:2, :1]

array([[ 1],
       [40]])

In [111]:
X=np.random.randn(10,2)
X

array([[-0.09873584,  1.5685531 ],
       [-1.21544273,  0.03797746],
       [-0.32719111, -0.98873815],
       [ 1.38305851, -1.60156645],
       [ 0.41180607,  0.0624533 ],
       [-1.34628536,  0.82147145],
       [ 0.60218499,  0.40294414],
       [ 0.86100272, -3.19194969],
       [ 0.30771398, -0.25195095],
       [-1.05398826,  0.44545606]])

In [118]:
X[0:5,:1]=X[0:5, :1]*np.zeros((5,1))
X

array([[-0.        ,  1.5685531 ],
       [-0.        ,  0.03797746],
       [-0.        , -0.98873815],
       [ 0.        , -1.60156645],
       [ 0.        ,  0.0624533 ],
       [-1.34628536,  0.82147145],
       [ 0.60218499,  0.40294414],
       [ 0.86100272, -3.19194969],
       [ 0.30771398, -0.25195095],
       [-1.05398826,  0.44545606]])

In [122]:
X[5: , 1:]=np.ones((5,1))
X

array([[-0.        ,  1.5685531 ],
       [-0.        ,  0.03797746],
       [-0.        , -0.98873815],
       [ 0.        , -1.60156645],
       [ 0.        ,  0.0624533 ],
       [-1.34628536,  1.        ],
       [ 0.60218499,  1.        ],
       [ 0.86100272,  1.        ],
       [ 0.30771398,  1.        ],
       [-1.05398826,  1.        ]])

In [14]:
# center the first 5 points at (-2,-2)
X[:5,:]=X[:5,:]-2*np.ones((5,2))

In [15]:
X[5:,:]=X[5:,:]+2*np.ones((5,2))

In [16]:
print(X)

array([[42, 37],
       [41,  3],
       [25, 26],
       [24, 18],
       [ 6, 36],
       [17, 34],
       [13, 18],
       [42,  5],
       [19, 28],
       [ 5, 41]])

In [17]:
# initialize a new matrix where first 50 elements are 0 and the next are 1
T=np.array([0]*5 +[1]*5)
T

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [18]:
ones =np.ones((10,1))
ones

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [19]:
Xb=np.concatenate((ones , X) , axis=1)

In [20]:
Xb

array([[  1.,  42.,  37.],
       [  1.,  41.,   3.],
       [  1.,  25.,  26.],
       [  1.,  24.,  18.],
       [  1.,   6.,  36.],
       [  1.,  17.,  34.],
       [  1.,  13.,  18.],
       [  1.,  42.,   5.],
       [  1.,  19.,  28.],
       [  1.,   5.,  41.]])

In [21]:
twos=4*np.ones((1,3))
twos

array([[ 4.,  4.,  4.]])

In [22]:
Xc=np.concatenate((twos, Xb) ,axis=0)

In [23]:
Xc

array([[  4.,   4.,   4.],
       [  1.,  42.,  37.],
       [  1.,  41.,   3.],
       [  1.,  25.,  26.],
       [  1.,  24.,  18.],
       [  1.,   6.,  36.],
       [  1.,  17.,  34.],
       [  1.,  13.,  18.],
       [  1.,  42.,   5.],
       [  1.,  19.,  28.],
       [  1.,   5.,  41.]])

In [24]:
A=np.random.randint(10,size= (5,2))
B=np.random.randint(5,size=(2))

In [25]:
A

array([[9, 1],
       [6, 5],
       [3, 5],
       [8, 1],
       [5, 1]])

In [26]:
B

array([4, 4])

In [27]:
w=A.dot(B)

In [28]:
w

array([40, 44, 32, 36, 24])

In [29]:
import numpy as np

N = 10
D = 2


X = np.random.randn(N,D)

# center the first 50 points at (-2,-2)
X[:5,:] = X[:5,:] - 2*np.ones((5,D))

# center the last 50 points at (2, 2)
X[5:,:] = X[5:,:] + 2*np.ones((5,D))
T = np.array([0]*5 + [1]*5)
ones = np.ones((N, 1))
Xb = np.concatenate((ones, X), axis=1)
w = np.random.randn(D + 1)
z = Xb.dot(w)

In [30]:
Xb

array([[ 1.        , -1.24791483, -4.4308033 ],
       [ 1.        , -1.03837646, -1.58941706],
       [ 1.        , -1.20460053, -2.95159056],
       [ 1.        , -1.97845861, -2.7551027 ],
       [ 1.        , -2.85956428, -1.43950754],
       [ 1.        ,  0.81236856,  3.64491361],
       [ 1.        ,  2.62536255,  2.72143051],
       [ 1.        ,  0.705591  ,  0.3892722 ],
       [ 1.        ,  1.39836971,  2.08237946],
       [ 1.        ,  1.88485926,  1.82831582]])

In [31]:
w

array([-1.60850226, -0.30434356,  0.30793986])

In [32]:
z

array([-2.59312838, -1.78192395, -2.15080224, -1.85477707, -1.18149404,
       -0.73332721, -1.56947752, -1.70337191, -1.39283944, -1.61913572])

In [33]:
z=Xb.dot(w)

In [34]:
z

array([-2.59312838, -1.78192395, -2.15080224, -1.85477707, -1.18149404,
       -0.73332721, -1.56947752, -1.70337191, -1.39283944, -1.61913572])

In [35]:
import numpy as np
a=np.array([1,3,5])

In [36]:
b=a.T
print(b)

[1 3 5]


In [37]:
a=np.random.randint(5,10, size=(5,3))
a

array([[5, 5, 7],
       [9, 6, 7],
       [6, 8, 6],
       [7, 8, 6],
       [5, 6, 9]])

In [38]:
b=a.T
print(b)

[[5 9 6 7 5]
 [5 6 8 8 6]
 [7 7 6 6 9]]


In [39]:
import numpy as np
a=np.array([1,2,3,4,5])
b=a.T
b

array([1, 2, 3, 4, 5])

In [40]:
b=np.array([1,2,3,4,5]).reshape(1,5)
c=b.T
c

array([[1],
       [2],
       [3],
       [4],
       [5]])

### In the first example of array where a=[1,3,5] when I take a transpose I was anticipating the row to become column but it did not , how ever it happened in the second example. In mathematics I can transpose 1*3 matrix to 3*1 matrix , so why would I not be able to do the same in numpy.